#!/bin/sh

set -euxo

sleep 2

file=$(cat - | jq -r '."source"')

echo '{"command": "start-judgement"}'
echo '{"command": "start-tab", "title": "Rendered"}'

content=$(cat $file)
jq --null-input \
  --arg description "$content" \
  '{"command": "append-message", "message": {"format": "markdown", "description": $description}}'

echo '{"command": "close-tab"}'
echo '{"command": "close-judgement", "accepted": true}'
