#!/bin/sh

set -eu

config=$(cat -)
file=$(jq -r '."source"' "$config")
language=$(jq -r '."natural_language"' "$config")

if [ "$language" = "nl" ]; then
  title="Gerenderd"
  empty="Lege oplossing"
else
  title="Rendered"
  empty="Empty submission"
fi

echo '{"command": "start-judgement"}'
echo "{\"command\": \"start-tab\", \"title\": \"$title\"}"

if [ -s "$file" ]; then
  content=$(cat "$file")
  jq --null-input \
    --arg description "$content" \
    '{"command": "append-message", "message": {"format": "markdown", "description": $description}}'
else
  echo "{\"command\": \"escalate-status\", \"status\": {\"enum\": \"wrong\", \"human\": \"$empty\"}}"
fi

echo '{"command": "close-tab"}'
echo '{"command": "close-judgement"}'
